name: Build and Release VPN Cluster

on:
  push:
    tags:
      - 'v*' # Запускать сборку только при создании тегов

# ДАЕМ ПРАВА НА СОЗДАНИЕ РЕЛИЗОВ И ЗАГРУЗКУ ФАЙЛОВ
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: false # ОТКЛЮЧАЕМ КЭШ, ЧТОБЫ УБРАТЬ ОШИБКУ ПРО go.sum

    - name: Download dependencies
      run: |
        go get github.com/xtls/xray-core@latest
        go mod tidy

    - name: Build Master
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o vpn-master ./cmd/master

    - name: Build Agent
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o vpn-agent ./cmd/agent

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          vpn-master
          vpn-agent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}